module:
  mounts:
    - source: assets
      target: assets
    - source: content
      target: content
    - source: data
      target: data
    - source: layouts
      target: layouts
    - source: static
      target: static
